---
#- name: Download and install the public Signing key
#  command: "curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-5.6.7-x86_64.rpm"


#- name: Install filebeat 
#  command: "rpm -vi filebeat-5.6.7-x86_64.rpm" 


#- name: Install libselinux python
#  yum :
#    name: libselinux-python
#    state: latest

- name: Configure filebeat
  template:
    src: filebeat.yml.j2 
    dest: /etc/filebeat/filebeat.yml 

- name: Start Filebeat
  command: "sudo /etc/init.d/filebeat start"
