---
# tasks file for ajgarlag.logstash
- name: adding logstash repository GPG key
  apt_key:
    url: https://packages.elasticsearch.org/GPG-KEY-elasticsearch

- name: adding logstash repository
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/5.x/apt stable main
    update_cache: yes

- name: Update the cache
  apt:
      update_cache: yes

- name: installing logstash
  apt:
    pkg: logstash
    state: latest

- name: Configure logstash
  template:
    src: logstash.conf.j2
    dest: /etc/logstash/conf.d/logstash.conf


- name: Start Logstash as a service now
  service:
    name: logstash
    state: restarted
