---
  - name: Create Ist ES Master Node instances
    ec2:
      key_name: "{{ aws_key_name }}"
      instance_type: "{{ aws_instance_type }}"
      image: "{{ aws_ami }}"
      wait: yes
      wait_timeout: 500
      instance_tags:
        Name: "{{ master_tag_name_1 }}"
      volumes:
        - device_name: /dev/sda1
          volume_type: gp2
          volume_size: 100
      vpc_subnet_id: "{{ subnet_ids[item] }}"
      region: "{{ aws_region }}"
      group: "{{ aws_sec_group_name }}"
    with_items:
      - a
    register: ec2_details_master_1

#  - name: Debug the variable name
#    debug:
#          var: ec2_details_master_1

  - name: Add Instances to local inventory file
    local_action:
      lineinfile path="~/ansible-environments/hosts"
        insertafter="\[esmaster\]"
        line="{{ item.private_ip }}"
        state="present"
    with_items: "{{ ec2_details_master_1.results[0].instances }}"


  - name: Create IInd ES Master Node instances
    ec2:
      key_name: "{{ aws_key_name }}"
      instance_type: "{{ aws_instance_type }}"
      image: "{{ aws_ami }}"
      wait: yes
      wait_timeout: 500
      instance_tags:
        Name: "{{ master_tag_name_2 }}"
      volumes:
        - device_name: /dev/sda1
          volume_type: gp2
          volume_size: 100
      vpc_subnet_id: "{{ subnet_ids[item] }}"
      region: "{{ aws_region }}"
      group: "{{ aws_sec_group_name }}"
    with_items:
      - b
    register: ec2_details_master_2

  - name: Add Instances to local inventory file
    local_action:
      lineinfile path="~/ansible-environments/hosts"
        insertafter="\[esmaster\]"
        line="{{ item.private_ip }}"
        state="present"
    with_items: "{{ ec2_details_master_2.results[0].instances }}"


  - name: Create IInd ES Master Node instances
    ec2:
      key_name: "{{ aws_key_name }}"
      instance_type: "{{ aws_instance_type }}"
      image: "{{ aws_ami }}"
      wait: yes
      wait_timeout: 500
      instance_tags:
        Name: "{{ master_tag_name_3 }}"
      volumes:
        - device_name: /dev/sda1
          volume_type: gp2
          volume_size: 100
      vpc_subnet_id: "{{ subnet_ids[item] }}"
      region: "{{ aws_region }}"
      group: "{{ aws_sec_group_name }}"
    with_items:
      - a
    register: ec2_details_master_3


  - name: Add Instances to local inventory file
    local_action:
      lineinfile path="~/ansible-environments/hosts"
        insertafter="\[esmaster\]"
        line="{{ item.private_ip }}"
        state="present"
    with_items: "{{ ec2_details_master_3.results[0].instances }}"


  - name: Destroy the Master-load balancer if already exists
    local_action:
      module: ec2_elb_lb
      name: "ops-master-nodes-elasticsearch"
      region: "{{ aws_region }}"
      state: absent
    ignore_errors: yes

  - name: Create a Classic Load balancer for Master nodes
    local_action:
      module: ec2_elb_lb
      name: "ops-master-nodes-elasticsearch"
      state: present
      scheme: internal
      region: "{{ aws_region }}"
      subnets:
        - subnet-9c3e38f8
        - subnet-a1654ed7
      listeners:
        - protocol: http
          load_balancer_port: 80
          instance_port: 80
    register: client_elb

  - name: Add the master instance behind the newly created load-balancer
    local_action:
      module: ec2_elb
      ec2_elbs: "ops-master-nodes-elasticsearch"
      instance_id: "{{ item }}"
      region: "{{ aws_region }}"
      state: present
    with_items:
      - "{{ ec2_details_master_1.results[0].instance_ids }}"
      - "{{ ec2_details_master_2.results[0].instance_ids }}"
      - "{{ ec2_details_master_3.results[0].instance_ids }}"
    ignore_errors: yes
