---
aws-key-name: "ansible-managed"
aws-sec-group-name:
    - "mayassar-es-external"
    - "elasticsearch-mayassar-production"
aws-instance-type: "m4.4xlarge"
aws-ami: "ami-b4a582e6"
aws-tag-name: "temp-nish"
subnet-id: "subnet-88d171ff"
