---
  - name: Run apt-get update_cache
    apt:
      update_cache: yes

  - name: Install Nginx on top of the Masters
    apt:
      name: nginx
      state: present

  - name: Configure Nginx to serve kibana
    template:
      src: default.j2
      dest: /etc/nginx/sites-available/default

  - name: Start Kibana as a service now
    service:
      name: nginx
      state: restarted
