---
  - name: Create EC2 instances
    ec2:
      key_name: "{{ aws_key_name }}"
      instance_type: "{{ aws_instance_type }}"
      image: "{{ aws_ami }}"
      wait: yes
      wait_timeout: 500
      count: 2
      instance_tags:
        Name: "{{ aws_tag_name }}"
      vpc_subnet_id: "{{ subnet_id }}"
      region: "{{ aws_region }}"
      group: "{{ aws_sec_group_name }}"
