---
  - name: Configure the Dedicated ES MASTER
    when: inventory_hostname in groups['esmaster']
    lineinfile:
      path: /etc/elasticsearch/elasticsearch.yml
      insertafter: EOF
      line: "{{ item }}"
    with_items:
      - 'node.master: true'
      - 'node.data: false'
      - 'node.ingest: false'

  - name: Re-Start Elasticsearch
    when: inventory_hostname in groups['esdata']
    service:
      name: elasticsearch
      state: restarted

  - name: Wait 10 sec to check if 9200 is alive
    when: inventory_hostname in groups['esdata']
    wait_for:
      port: 9200
      delay: 10


  - name: Check if ES is running or FAIL here
    when: inventory_hostname in groups['esdata']
    command: 'curl http://"{{ inventory_hostname }}":9200'
    register: curl_result
    failed_when: "'Failed' in curl_result.stderr"
