---
  - name: Install Python first
    raw:  test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

  - name: Run apt-get update & upgrade
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400
