---
aws_key_name: "ansible-managed"
aws_sec_group_name:
    - "mayassar-es-external"
    - "elasticsearch-mayassar-production"
aws_instance_type: "m4.4xlarge"
aws_ami: "ami-b4a582e6"  # this is currently a CentOS image , need to discuss for ubuntu
master_tag_name: "Kill-master-es"
data_tag_name: "Kill-data-es"
client_tag_name: "Kill-client-es"
subnet_id: "subnet-88d171ff"
aws_region: "ap-southeast-1"
master_instance_count: 1
data_instance_count: 2
client_instance_count: 1
startindex: 1
