---
  - name: Run apt-get update
    apt:
      update_cache: yes

  - name: Update all packages to the latest version
    apt:
      upgrade: dist

  - name: Add an Apt signing key, uses whichever key is at the URL
    apt_key:
      url: https://swupdate.openvpn.net/repos/repo-public.gpg
      state: present

  - name: Create the apt source list file
    file:
      path: /etc/apt/sources.list.d/openvpn-aptrepo.list
      state: touch

  - name: Add the deb to source list
    shell: |
       echo "deb http://build.openvpn.net/debian/openvpn/stable xenial main" > /etc/apt/sources.list.d/openvpn-aptrepo.list

  - name: Run apt-get update
    apt:
      update_cache: yes

  - name: Install OpenVPN and more
    apt:
        name: "{{ item }}"
    with_items:
      - openvpn
      - easy-rsa
      - libpam-google-authenticator
      - iptables-persistent

  - name: Copy the easy-rsa files
    command: cp -r /usr/share/easy-rsa/ /etc/openvpn/

  - name: Get my public IP
    ipify_facts:

  - debug: var=ipify_public_ip

  - name: Replace the lines in vars
    lineinfile:
      dest: /etc/openvpn/easy-rsa/vars
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items:
      - { regexp: '^export KEY_COUNTRY=', line: 'export KEY_COUNTRY="IN"' }
      - { regexp: '^export KEY_PROVINCE=', line: 'export KEY_PROVINCE="ND"' }
      - { regexp: '^export KEY_CITY=', line: 'export KEY_CITY="Delhi"' }
      - { regexp: '^export KEY_ORG=', line: 'export KEY_ORG="Paytm"' }
      - { regexp: '^export KEY_OU=', line: 'export KEY_OU="DAAS"' }
      - { regexp: '^export KEY_NAME=', line: 'export KEY_NAME="Paytm LAB VPN"' }
      - { regexp: '^export VPN_HOSTNAME=', line: 'export VPN_HOSTNAME="{{ ipify_public_ip }}"' }

  - name: Remove Interactivity of the build script
    shell: |
      sed -i "s/--interact //g" /etc/openvpn/easy-rsa/build-*

  - name: UFW rules
    lineinfile:
      path: /etc/default/ufw
      regexp: '^DEFAULT_FORWARD_POLICY'
      line: 'DEFAULT_FORWARD_POLICY="ACCEPT"'

  - name: Run ufw commands
    command: "{{ item }}"
    with_items:
      - ufw allow 1194/udp
      - ufw allow OpenSSH
      - ufw disable
      - ufw enable

  - name: Transfer the script
    copy: src=configure.sh dest=/home/ubuntu mode=0777

  - name: Execute the shell script
    command: sudo /home/ubuntu/configure.sh

  - name: Restart OpenVPN
    command: "service openvpn@server status"
